### ISSUE TITLE
Add support for multiline comments

### ISSUE THREAD

**Issue by ghost** [allenta/gitlab-listener#9]
It would be nice if you could support multi-line comments as currently putting everything in one line is quite limiting.

Some ideas for implementation:
- Add additional tags for multiline comment support, for example:
  
  .#time# 1d 2h 3m This is a multiline comment which will be
  parsed as multiline due to a special tag that we use. It will be
  displayed in JIRA as multi-line comment aswell. The comment 
  could be parsed until the end of commit or until it will see closing
  of special tag #time#
- Just special block tag for multiline commend start and end that can be used with any of the existing tags (like #mstart #mend), for example:
  
  .#time 1d 2h 3m #mstart This is a multiline comment which will be 
  parsed correctly by the plugin and added to jira #mend 

Anything else that you see possible or can come up with would be appreciated.

**Comment by carlosabalde** [comment]
On the one hand, contents of JIRA comments / activities generated by the add-on are intentionally restricted to the first line of the commit message. There are two reasons for this:
1. The goal of the add-on is not replicating data already available in GitLab. The goal is linking to that existing data from JIRA.
2. It's a common best practice when writing commit messages splitting messages in two parts: the first line, treated as the subject of the commit, and the rest of the text, treated as the body.

On the other hand, JIRA worklog entries generated by the add-on are also restricted to the first line of the message included in the `#time` directive. I agree not using the whole message in this particular case is not a great idea. I think we could simply use the whole message included in `#time` directive and avoid adding more tags.

Do you agree?

**Comment by ghost** [comment]
> On the one hand, contents of JIRA comments / activities generated by the add-on are intentionally restricted to the first line of the commit message. 

I find that #time and #action tags are not restricted to first line of commit message only. Example commit that works:

```
   JIRA-XX Some commit message

   #time 1d 2h 3m Worklog message
```

> I think we could simply use the whole message included in #time directive and avoid adding more tags.
> 
> Do you agree?

What do you mean by "use the whole message included in #time directive"? Does this mean that all the lines after #time directive will be included? If so, I agree.

**Comment by carlosabalde** [comment]
A new version (1.1.7) of the add-on including this is now available in the Atlassian Marketplace. Thanks!

**Comment by ghost** [comment]
I will test this, thank you. Great Addon by the way.

**Comment by jcglqmoyx** [comment]
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/
menu:
  home: https://jcglqmoyx.github.io/
  About:
  Articles:
  archives:

# Site
title: Chintsai
subtitle: It's never too old to learn.
description: It's never too old to learn.
keywords: Chintsai
author: Chintsai
language: en
timezone: 

# 自动生成sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://jcglqmoyx.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next
plugins: hexo-generate-feed

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy: 
  type: git
  repo: git@github.com:jcglqmoyx/jcglqmoyx.github.io.git
  branch: master
```
